pipeline {
    agent any

    environment {
        IMAGE_NAME = "priyabratakhandual/dealer-backend"
        IMAGE_TAG  = "${BUILD_NUMBER}"
        GITOPS_REPO = "https://github.com/priyabratakhandual/gitops.git"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    '''
                }
            }
        }

        stage('Build Image') {
            steps {
                dir('backend') {
                    sh '''
                        docker-compose build
                    '''
                }
            }
        }

        stage('Tag Image') {
            steps {
                sh '''
                    docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                    docker push ${IMAGE_NAME}:latest
                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }

        stage('Create Kubernetes Secret') {
            steps {
                withCredentials([
                    file(credentialsId: 'backend-env', variable: 'ENV_FILE')
                ]) {
                    sh '''
                        kubectl create secret generic backend-secret \
                          --from-env-file=$ENV_FILE \
                          -n dealing \
                          --dry-run=client -o yaml | kubectl apply -f -
                    '''
                }
            }
        }

        stage('Update GitOps Repository') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'github-token',
                        usernameVariable: 'GIT_USER',
                        passwordVariable: 'GIT_TOKEN'
                    )
                ]) {

                    sh '''
                        rm -rf gitops

                        git clone https://${GIT_USER}:${GIT_TOKEN}@github.com/priyabratakhandual/gitops.git

                        cd gitops/deal

                        sed -i "s/tag:.*/tag: \\"${IMAGE_TAG}\\"/" values.yaml

                        git config user.name "Jenkins"
                        git config user.email "jenkins@local"

                        git add values.yaml

                        git commit -m "Update backend image ${IMAGE_TAG}" || true

                        git push origin master
                    '''
                }
            }
        }

    }

    post {

        success {
            echo "Backend deployed successfully through GitOps."
        }

        always {
            sh '''
                docker logout
            '''
        }

    }
}